AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  login:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: login.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::726890182035:role/lambda-vpc-execution-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /login
            Method: ANY
      VpcConfig:
        SecurityGroupIds:
          - sg-04a153ed668f58546
        SubnetIds:
          - subnet-0f4951494e4b03aff
          - subnet-0490c6a736d1a99a7
